repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: machine_learning_projects
      - id: check-ast
        exclude: machine_learning_projects
      - id: check-case-conflict
      - id: debug-statements
        exclude: machine_learning_projects
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.2
    hooks:
      - id: autopep8
        exclude: machine_learning_projects

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
      - id: add-trailing-comma
