name: tabular_ml_env
channels:
  - conda-forge
  - nodefaults

dependencies:
  # base env
  - python >=3.11
  - jupyterlab
  - nodejs
  - ipympl

  # data libraries
  - pandas
  - numpy
  - scipy
  - pyarrow

  # ml libraries
  - scikit-learn
  - optuna
  - xgboost
  - catboost
  - lightgbm

  # viz libraries
  #- seaborn
  #- holoviews
  #- hvplot
  #- seaborn

  # dev tools
  - jupyterlab-lsp
  - python-lsp-server
  - pytest
  - pre-commit

  # library managment
  - conda
  - conda-build
  - mamba
  - pip
