name: tabular_machine_learning
channels:
  - conda-forge
  - pytorch
  - nodefaults

dependencies:
  # base env
  - python =3.11
  - jupyterlab
  - nodejs
  - ipympl
  - jupyterlab-lsp
  - python-lsp-server

  # data libraries
  - pandas
  - numpy
  - scipy
  - pyarrow

  # ml libraries
  - scikit-learn
  - optuna
  - xgboost
  - catboost
  - lightgbm
  - pytorch

  # viz libraries
  - seaborn
  - holoviews
  - hvplot
  - seaborn

  # library managment
  - conda
  - conda-build
  - mamba
  - pip


  